const $=s=>document.querySelector(s);let universities=[],reviews=[];
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function isSecond(v){return String(v||'').toLowerCase().startsWith('tak')}
function link(url,label){return url?`<a class="btn" target="_blank" rel="noopener" href="${esc(url)}">${label}</a>`:''}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function aliasesFor(u){let aliases=[u.Uczelnia,u.id];const n=norm(u.Uczelnia+' '+(u['Pełny tytuł kierunku']||''));if(n.includes('atins')||n.includes('wyzsza szkola informatyki'))aliases.push('ATINS Wrocław','Atins Wrocław','Wrocławska Wyższa Szkoła Informatyki Stosowanej / ATINS','Wrocławska Wyższa Szkoła Informatyki Stosowanej');if(n.includes('pjatk')||n.includes('polsko japonska'))aliases.push('Podyplomowe PJATK','PJATK','Polsko-Japońska Akademia Technik Komputerowych');if(n.includes('politechnika wroclawska'))aliases.push('Politechnika Wrocławska (II stopień)');return aliases.map(norm)}
function reviewsFor(u){const aliases=aliasesFor(u);return reviews.filter(r=>{const rn=norm(r.university);const dn=norm(r.degree);return aliases.includes(rn)||aliases.some(a=>a&&(rn.includes(a)||a.includes(rn)))||(norm(u.Uczelnia).includes('uniwersytet warszawski')&&rn.startsWith('uniwersytet warszawski'))||(aliases.includes('pjatk')&&(rn.includes('pjatk')||dn.includes('podyplomowe')))}).sort((a,b)=>String(b.year||'2024').localeCompare(String(a.year||'2024')))}
function renderStats(){const second=universities.filter(x=>isSecond(x['Czy jest II stopień na tej samej uczelni?'])).length;const cities=new Set(universities.map(u=>u.Miasto).filter(Boolean)).size;$('#top').innerHTML=`<div class="panel stat"><b>${universities.length}</b><small>uczelni w bazie</small></div><div class="panel stat"><b>${reviews.length}</b><small>opinii</small></div><div class="panel stat"><b>${cities}</b><small>miast</small></div>`}
function render(){const q=$('#q').value.toLowerCase().trim(),typ=$('#type').value.toLowerCase(),sec=$('#second').value,sort=$('#sort').value;let list=universities.map(u=>({...u,_reviews:reviewsFor(u)})).filter(u=>{const text=JSON.stringify(u).toLowerCase()+' '+u._reviews.map(r=>r.comment).join(' ').toLowerCase();if(q&&!text.includes(q))return false;if(typ&&String(u['Typ oferty']).toLowerCase()!==typ)return false;if(sec==='tak'&&!isSecond(u['Czy jest II stopień na tej samej uczelni?']))return false;if(sec==='nie'&&isSecond(u['Czy jest II stopień na tej samej uczelni?']))return false;return true});list.sort((a,b)=>sort==='name'?a.Uczelnia.localeCompare(b.Uczelnia,'pl'):b._reviews.length-a._reviews.length);$('#cards').innerHTML=list.length?list.map(card).join(''):'<div class="panel empty">Brak wyników dla tych filtrów.</div>';document.querySelectorAll('[data-toggle]').forEach(btn=>btn.onclick=()=>{const el=document.getElementById(btn.dataset.toggle);el.style.display=el.style.display==='block'?'none':'block'})}
function card(u){const rs=u._reviews,id='d-'+u.id;const secondVal=u['Czy jest II stopień na tej samej uczelni?']||'—';const secondClass=isSecond(secondVal)?'good':'warn';return `<article class="card"><h2>${esc(u.Uczelnia)}</h2><div class="small"><b>${esc(u['Pełny tytuł kierunku']||'—')}</b> · oferta: ${esc(u['Rok oferty']||'—')}</div><div class="meta"><span class="pill">${esc(u['Typ oferty']||'—')}</span><span class="pill">${esc(u['Tytuł po ukończeniu']||'—')}</span><span class="pill">${esc(u['Czas trwania']||'—')}</span><span class="pill ${secondClass}">II stopień: ${esc(secondVal)}</span><span class="pill">opinii: ${rs.length}</span></div><p class="small"><b>Rekrutacja:</b> ${esc(u['Wymagane przedmioty maturalne / rekrutacja']||'—')}</p><div class="links">${link(u['Link do pełnej oferty'],'Oferta')}${link(u['Link do spisu przedmiotów'],'Spis przedmiotów')}${link(u['Link do planu zajęć'],'Plan zajęć')}<button data-toggle="${id}">Szczegóły i opinie</button></div><div class="details" id="${id}"><table><tr><th>Miasto</th><td>${esc(u.Miasto||'—')}</td></tr><tr><th>Typ oferty</th><td>${esc(u['Typ oferty']||'—')}</td></tr><tr><th>Czas trwania</th><td>${esc(u['Czas trwania']||'—')}</td></tr><tr><th>Tytuł po ukończeniu</th><td>${esc(u['Tytuł po ukończeniu']||'—')}</td></tr><tr><th>II stopień na tej samej uczelni</th><td>${esc(secondVal)}</td></tr><tr><th>Rekrutacja</th><td>${esc(u['Wymagane przedmioty maturalne / rekrutacja']||'—')}</td></tr></table><div class="notice"><strong>Uwaga:</strong> opinie są subiektywne i nie są oficjalnym stanowiskiem uczelni.</div>${rs.length?rs.map(r=>`<div class="review"><span class="pill">${esc(r.year||'2024')}</span>${r.level?' <span class="small">· '+esc(r.level)+'</span>':''}<p>${esc(r.comment)}</p></div>`).join(''):'<p class="small">Brak opinii — dodaj pierwszą.</p>'}</div></article>`}
async function init(){const [u,r]=await Promise.all([fetch('universities.json?v=8').then(x=>x.json()),fetch('reviews.json?v=8').then(x=>x.json())]);universities=u.universities||[];reviews=r.reviews||[];renderStats();render();['q','type','second','sort'].forEach(id=>$('#'+id).addEventListener('input',render))}init().catch(e=>{$('#cards').innerHTML='<div class="panel empty">Nie udało się wczytać danych. Uruchom przez GitHub Pages albo lokalny serwer.</div>';console.error(e)});
